### ISSUE TITLE
Freecam movement speed

### ISSUE THREAD

**Issue by raydeejay** [GT3CH1/minecraft-mod#53]
**Describe the bug**
Freecam moves too slowly in the horizontal plane, and maybe too fast in the vertical axis.

**To Reproduce**
Enable freecam.

**Expected behavior**
Horizontal movement faster or the same speed as vertical movement.

**Version Info (please complete the following information):**
1.4.1

**Comment by GT3CH1** [comment]
Thanks.  I will look into this.

**Comment by GT3CH1** [comment]
What would you suggest be a comfortable speed for this? or would a user-controllable speed be something that would be nice to have?

**Comment by raydeejay** [comment]
I suppose this is a rather subjective thing, if I had to choose one option I'd say variable speed in the way spectator mode works, but then I'm not the one implementing it :grin:

At the very least it should be equivalent to walking speed. The upper limit doesn't have to be very high because the world around the player is presumably only a few chunks in each direction.

**Comment by GT3CH1** [comment]
No worries! I will take a look at it when I get some time.

**Comment by raydeejay** [comment]
Since you're going to go over this anyway... two more things!

1/ shouldn't the player be able to phase into solid blocks when in freecam? (it is possible if NoClip is enabled)
2/ disabling freecam (even without activating Fly) leaves the player in flying state

**Comment by GT3CH1** [comment]
Thank you for your comment.  Here are my thoughts on your questions.

1) I've thought about this - I'm mixed between allowing the player to no-clip when free-cam is enabled, or have it toggleable through the no-clip feature itself. Other clients  have it enabled automatically. It's trivial to have it be enabled when FreeCam is enabled/disabled, but then again I'm conflicted whether to allow this, as I prefer the features to be enabled/disable explicitly by the player rather than have some turn on automatically.

2) I have addressed this issue. Thanks for informing me about it.

As for the FreeCam speed, I have implemented a setting to allow the user to change the scaling on it. There is one issue with it at the present moment - but it is a very minor one at best which may/may not get patched.

**Comment by raydeejay** [comment]
If your intention is for the player to combine NoClip and FreeCam when they want, then I'd say leave it at that, it's definitely not a deal breaker!

There may be more reports as I keep trying things... :grin:

**Comment by GT3CH1** [comment]
No worries! Bring them on! I'm just thrilled that someone out there is using my mod. There are a few housekeeping items I need to take care of before I release a version with the fix for this particular issue (ie, updating the readme with build instructions and such). So if you run into any more weird or strange things, please open another issue. In the mean time, I will be closing this one as the primary problem has been fixed and the fix exists in the `1.19.4-dev` branch. Thanks!
