### ISSUE TITLE
ESP not rendering

### ISSUE THREAD

**Issue by raydeejay** [GT3CH1/minecraft-mod#54]
**Describe the bug**
There are no boxes around the targets

**To Reproduce**
Enable some ESPs

**Expected behavior**
A box is drawn around selected targets

**Screenshots/Video**
Attached a screenshot

**Version Info (please complete the following information):**
1.4.1+1.19.4
![Screenshot at 2023-03-19 21-47-10](https://user-images.githubusercontent.com/1245743/226211799-ebc649b6-029e-4c1d-89e9-03645e322c93.png)

**Comment by GT3CH1** [comment]
This might be a problem with the alpha value. Please ensure that the ESP alpha is turned up.

**Comment by raydeejay** [comment]
I set both tracers and ESP to maximum alpha, the tracers show but the ESP boxes don't.

**Comment by GT3CH1** [comment]
Could you attach a crash report? Press Shift+F3+C for 10 seconds and it will cause Minecraft to crash.  It contains information that might allow me to reproduce this.

**Comment by raydeejay** [comment]
[crash-2023-03-19_22.42.19-client.txt](https://github.com/GT3CH1/minecraft-mod/files/11012497/crash-2023-03-19_22.42.19-client.txt)

**Comment by GT3CH1** [comment]
This appears to be related to sodium as I was able to reproduce it when I had the mod installed. I'm exploring possible options for this. It may/may not be fixed.

**Comment by GT3CH1** [comment]
I was able to re-write the ESP render engine so that it does not use methods that are overridden by performance mods such as sodium, the culprit for this bug. I also was able to confirm that the patch fixes this bug by installing my mod + sodium together, and enabled all the ESP's and confirmed it was working. I will close this issue when PR #57  gets merged into the 1.19.4 mainline branch.

**Comment by GT3CH1** [comment]
Hi,
just updating the status on this - I have merged this into `1.19.4-dev` and plan on merging that into the mainline branch this weekend/early next weekend. I _may_ rework the way that ESP/tracers work to have a menu like XRay for selecting what entities are shown, if I do that, it may delay the release by a bit. But as of now - this issue is fixed and I will be closing it. Thanks again!

**Comment by raydeejay** [comment]
I was just thinking yesterday about that particular feature, so... I guess now you can't say no one asked for it :grin:

**Comment by GT3CH1** [comment]
It's been on my docket for a while now! I think it'll be a lot better than
toggles...
